export interface FakeProfile {
  id: string
  name: string
  title: string
  company: string
  industry: string
  avatarUrl: string
}

function p(id: number, name: string, title: string, company: string, industry: string): FakeProfile {
  return { id: `p${id}`, name, title, company, industry, avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(name)}&mouth=smile&eyes=happy` }
}

const profiles: FakeProfile[] = [
  p(1, "Sarah Chen", "VP of Engineering", "Stripe", "FinTech"),
  p(2, "Marcus Johnson", "Founder & CEO", "NovaTech", "AI & Machine Learning"),
  p(3, "Priya Patel", "Data Scientist", "DeepMind", "AI & Machine Learning"),
  p(4, "James Wright", "Product Manager", "Figma", "Design"),
  p(5, "Amara Osei", "Investment Analyst", "a16z", "Finance"),
  p(6, "Liam O'Connor", "Software Engineer", "Vercel", "Technology"),
  p(7, "Mei Lin", "UX Researcher", "Apple", "Technology"),
  p(8, "Carlos Rivera", "Growth Lead", "Notion", "Marketing"),
  p(9, "Fatima Hassan", "ML Engineer", "OpenAI", "AI & Machine Learning"),
  p(10, "David Kim", "CTO", "Watershed", "Energy"),
  p(11, "Elena Petrov", "Venture Partner", "Sequoia Capital", "Finance"),
  p(12, "Raj Mehta", "Backend Engineer", "Supabase", "Technology"),
  p(13, "Sophie Laurent", "Brand Strategist", "Nike", "Marketing"),
  p(14, "Aiden Murphy", "DevOps Lead", "Datadog", "Technology"),
  p(15, "Yuki Tanaka", "Research Scientist", "Google Brain", "AI & Machine Learning"),
  p(16, "Olivia Brown", "Legal Counsel", "Coinbase", "Blockchain & Crypto"),
  p(17, "Noah Williams", "Product Designer", "Spotify", "Design"),
  p(18, "Ava Martinez", "Operations Manager", "Flexport", "Manufacturing"),
  p(19, "Ethan Taylor", "Sales Director", "Salesforce", "Sales"),
  p(20, "Zara Ahmed", "Biotech Researcher", "Moderna", "Healthcare"),
  p(21, "Daniel Park", "iOS Developer", "Airbnb", "Technology"),
  p(22, "Isabella Rossi", "Marketing Director", "HubSpot", "Marketing"),
  p(23, "William Chen", "Quant Analyst", "Citadel", "Finance"),
  p(24, "Grace Kim", "Frontend Engineer", "Netflix", "Technology"),
  p(25, "Lucas Santos", "Founder", "TechFlow", "Startups"),
  p(26, "Emma Davis", "HR Director", "Shopify", "HR & Recruiting"),
  p(27, "Omar Hassan", "Cloud Architect", "AWS", "Technology"),
  p(28, "Chloe Martin", "Content Strategist", "Buffer", "Marketing"),
  p(29, "Ryan Patel", "Data Engineer", "Snowflake", "Technology"),
  p(30, "Hannah Lee", "UX Designer", "Canva", "Design"),
  p(31, "Nathan Brooks", "Security Engineer", "CrowdStrike", "Cybersecurity"),
  p(32, "Maya Gupta", "Product Lead", "Slack", "Technology"),
  p(33, "Chris Anderson", "VP Sales", "Twilio", "Sales"),
  p(34, "Lily Zhang", "AI Researcher", "Anthropic", "AI & Machine Learning"),
  p(35, "Jack Robinson", "Full Stack Dev", "GitHub", "Technology"),
  p(36, "Sophia Wilson", "CFO", "Plaid", "Finance"),
  p(37, "Alex Turner", "Design Lead", "Framer", "Design"),
  p(38, "Nadia Kowalski", "Data Analyst", "Tableau", "Technology"),
  p(39, "Benjamin Lee", "Eng Manager", "Uber", "Technology"),
  p(40, "Aria Nakamura", "Researcher", "MIT Media Lab", "Education"),
  p(41, "Oliver Grant", "Account Executive", "Gong", "Sales"),
  p(42, "Samira Patel", "Biostatistician", "Pfizer", "Healthcare"),
  p(43, "Thomas Weber", "Platform Engineer", "Docker", "Technology"),
  p(44, "Victoria Chang", "Creative Director", "Adobe", "Design"),
  p(45, "Hugo Fernandez", "Mobile Dev", "DoorDash", "Technology"),
  p(46, "Julia Andersson", "Sustainability Lead", "Patagonia", "Energy"),
  p(47, "Kevin Okafor", "Blockchain Dev", "Polygon", "Blockchain & Crypto"),
  p(48, "Rachel Green", "PR Manager", "Edelman", "Marketing"),
  p(49, "Andre Williams", "Solutions Architect", "Google Cloud", "Technology"),
  p(50, "Diana Popov", "Clinical Researcher", "Mayo Clinic", "Healthcare"),
  p(51, "Matthew Scott", "CEO", "BuildRight", "Construction"),
  p(52, "Isabelle Dupont", "Fashion Designer", "Chanel", "Fashion & Beauty"),
  p(53, "Jason Ng", "Firmware Engineer", "Tesla", "Automotive"),
  p(54, "Lena Schmidt", "Recruiter", "LinkedIn", "HR & Recruiting"),
  p(55, "Patrick O'Brien", "Consultant", "McKinsey", "Consulting"),
  p(56, "Monica Reyes", "Nutritionist", "Noom", "Healthcare"),
  p(57, "Derek Chang", "Game Developer", "Riot Games", "Entertainment & Media"),
  p(58, "Alicia Torres", "Immigration Lawyer", "Fragomen", "Legal"),
  p(59, "Brian Foster", "Civil Engineer", "AECOM", "Construction"),
  p(60, "Priscilla Wu", "Economist", "World Bank", "Government"),
  p(61, "Steven Park", "Robotics Engineer", "Boston Dynamics", "Technology"),
  p(62, "Carmen Lopez", "Social Media Lead", "TikTok", "Marketing"),
  p(63, "Henry Liu", "Venture Analyst", "Y Combinator", "Finance"),
  p(64, "Nicole Adams", "Supply Chain Mgr", "Amazon", "Manufacturing"),
  p(65, "George Miller", "CIO", "JPMorgan", "Finance"),
  p(66, "Ananya Sharma", "NLP Engineer", "Cohere", "AI & Machine Learning"),
  p(67, "Tyler Brooks", "Sports Analyst", "ESPN", "Sports & Fitness"),
  p(68, "Mia Costa", "Interior Designer", "Gensler", "Design"),
  p(69, "Jake Morrison", "Pilot", "Delta Airlines", "Travel & Hospitality"),
  p(70, "Sara Johansson", "Pharmacist", "CVS Health", "Healthcare"),
  p(71, "Ravi Kumar", "SRE", "PagerDuty", "Technology"),
  p(72, "Claire Beaumont", "Chef", "Eleven Madison", "Food & Beverage"),
  p(73, "Douglas West", "Insurance Analyst", "AIG", "Finance"),
  p(74, "Tanya Ivanova", "Geneticist", "23andMe", "Healthcare"),
  p(75, "Franklin Lee", "Tax Attorney", "Deloitte", "Legal"),
  p(76, "Hana Yoshida", "Animator", "Pixar", "Entertainment & Media"),
  p(77, "Roberto Silva", "Telecom Engineer", "Ericsson", "Telecommunications"),
  p(78, "Elise Martin", "Copywriter", "Ogilvy", "Marketing"),
  p(79, "Kwame Mensah", "Agritech Lead", "Indigo Ag", "Food & Beverage"),
  p(80, "Lisa Chang", "Dermatologist", "NYU Langone", "Healthcare"),
  p(81, "Nick Thompson", "Sports Coach", "Nike Training", "Sports & Fitness"),
  p(82, "Bianca Ferreira", "Jewelry Designer", "Tiffany & Co", "Fashion & Beauty"),
  p(83, "Ian McGregor", "Defense Analyst", "Lockheed Martin", "Aerospace & Defense"),
  p(84, "Valentina Cruz", "Teacher", "Khan Academy", "Education"),
  p(85, "Adam Wheeler", "Real Estate Dev", "Hines", "Real Estate"),
  p(86, "Jenna Park", "Epidemiologist", "CDC", "Healthcare"),
  p(87, "Oscar Hernandez", "DJ / Producer", "Independent", "Entertainment & Media"),
  p(88, "Freya Nilsson", "Climate Scientist", "NASA", "Energy"),
  p(89, "Leo Tanaka", "Venture Builder", "Antler", "Startups"),
  p(90, "Michelle Obi", "Policy Analyst", "Brookings", "Government"),
  p(91, "Peter Kang", "Payments Engineer", "Square", "FinTech"),
  p(92, "Natasha Volkov", "Ballet Director", "ABT", "Entertainment & Media"),
  p(93, "Richard Hayes", "COO", "WeWork", "Real Estate"),
  p(94, "Dina Mahmoud", "Oncologist", "Sloan Kettering", "Healthcare"),
  p(95, "Sebastian Muller", "Auto Engineer", "BMW", "Automotive"),
  p(96, "Aurora Bianchi", "Sommelier", "Per Se", "Food & Beverage"),
  p(97, "Travis King", "Esports Manager", "Cloud9", "Entertainment & Media"),
  p(98, "Yara El-Amin", "Architect", "Zaha Hadid", "Construction"),
  p(99, "Colin Fraser", "Marine Biologist", "Oceana", "Energy"),
  p(100, "Leila Nazari", "Nonprofit Director", "UNICEF", "Nonprofit"),
  // 5 additional nodes
  p(101, "Tariq Al-Rashid", "Venture Capital Partner", "Tiger Global", "Finance"),
  p(102, "Sienna Blake", "Head of Product", "Figma", "Design"),
  p(103, "Dmitri Volkov", "Principal Engineer", "Meta", "Technology"),
  p(104, "Aisha Mbeki", "Growth Marketing Lead", "Canva", "Marketing"),
  p(105, "Chen Wei", "Founding Engineer", "Mistral AI", "AI & Machine Learning"),
  // 50 additional nodes
  p(106, "Marta Silva", "Data Analyst", "Spotify", "Technology"),
  p(107, "Jared Okonkwo", "Supply Chain Director", "Amazon", "Logistics"),
  p(108, "Elena Petrova", "UX Researcher", "Airbnb", "Design"),
  p(109, "Kai Nakamura", "Robotics Engineer", "Boston Dynamics", "Engineering"),
  p(110, "Priya Sharma", "Investment Banker", "JPMorgan", "Finance"),
  p(111, "Lucas Bennett", "Film Editor", "Netflix", "Entertainment & Media"),
  p(112, "Zara Hussain", "DevOps Lead", "HashiCorp", "Technology"),
  p(113, "Marco Rossi", "Head Chef", "Noma", "Food & Beverage"),
  p(114, "Amara Diallo", "Social Impact Manager", "Patagonia", "Nonprofit"),
  p(115, "Ethan Cho", "Quantitative Trader", "Jane Street", "Finance"),
  p(116, "Sofia Andersson", "Biotech Researcher", "Moderna", "Healthcare"),
  p(117, "Omar Farouk", "AI Ethics Researcher", "DeepMind", "AI & Machine Learning"),
  p(118, "Isla MacDonald", "Brand Strategist", "Nike", "Marketing"),
  p(119, "Ryan Patel", "Cloud Architect", "Snowflake", "Technology"),
  p(120, "Nina Gustafsson", "Fashion Buyer", "Net-a-Porter", "Retail"),
  p(121, "Carlos Mendez", "Civil Engineer", "Bechtel", "Construction"),
  p(122, "Hannah Liu", "Pediatric Surgeon", "Children's Hospital", "Healthcare"),
  p(123, "Viktor Kozlov", "Game Designer", "Riot Games", "Gaming"),
  p(124, "Fatima Al-Sayed", "Sustainability Director", "Unilever", "Consumer Goods"),
  p(125, "Jack Morrison", "Sports Agent", "CAA", "Sports"),
  p(126, "Yuki Watanabe", "Manga Artist", "Shueisha", "Entertainment & Media"),
  p(127, "Rebecca Stone", "Chief of Staff", "Anthropic", "AI & Machine Learning"),
  p(128, "Andre Williams", "Music Producer", "Atlantic Records", "Entertainment & Media"),
  p(129, "Lena Fischer", "Aerospace Engineer", "Boeing", "Aerospace"),
  p(130, "Samuel Osei", "EdTech Founder", "Andela", "Education"),
  p(131, "Chloe Dubois", "Luxury Brand Manager", "LVMH", "Retail"),
  p(132, "Tomas Navarro", "Neuroscientist", "MIT", "Research"),
  p(133, "Ingrid Bergman", "Energy Trader", "Shell", "Energy"),
  p(134, "David Kim", "Staff Engineer", "Stripe", "FinTech"),
  p(135, "Aaliya Rahman", "HR Director", "Deloitte", "Consulting"),
  p(136, "Max Richter", "Sound Designer", "Dolby", "Technology"),
  p(137, "Gabriella Torres", "Immigration Lawyer", "Baker McKenzie", "Legal"),
  p(138, "Benjamin Hart", "Cryptography Researcher", "Signal", "Security"),
  p(139, "Mei-Lin Chang", "VC Associate", "a16z", "Venture Capital"),
  p(140, "Patrick O'Brien", "Brewmaster", "Guinness", "Food & Beverage"),
  p(141, "Nadia Kovalenko", "Ballet Dancer", "Bolshoi Theatre", "Performing Arts"),
  p(142, "James Wright", "Investigative Journalist", "Reuters", "Media"),
  p(143, "Sakura Ito", "Cosmetics Chemist", "Shiseido", "Consumer Goods"),
  p(144, "Emmanuel Adeyemi", "Mobile Engineer", "Uber", "Technology"),
  p(145, "Clara Johansson", "Industrial Designer", "IKEA", "Design"),
  p(146, "Diego Vargas", "Coffee Buyer", "Blue Bottle", "Food & Beverage"),
  p(147, "Anika Gupta", "Telecommunications VP", "Ericsson", "Telecom"),
  p(148, "Tyler Brooks", "Physical Therapist", "Mayo Clinic", "Healthcare"),
  p(149, "Lina Berglund", "Quantum Computing Researcher", "IBM", "Research"),
  p(150, "Chris Donovan", "Talent Scout", "YC", "Startups"),
  p(151, "Rana Hashemi", "Documentary Filmmaker", "A24", "Entertainment & Media"),
  p(152, "Felix Braun", "Automotive Designer", "Porsche", "Automotive"),
  p(153, "Julia Santos", "Microbiologist", "WHO", "Healthcare"),
  p(154, "Nathan Cole", "Real Estate Developer", "Brookfield", "Real Estate"),
  p(155, "Emilia Novak", "Orchestra Conductor", "Berlin Philharmonic", "Performing Arts"),
]

export default profiles
